name: Fullstack Deployment to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install backend dependencies
        run: pip install -r requirements.txt

      - name: Zip backend artifact for deployment
        run: zip -r backend.zip app.py prompt.txt requirements.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend.zip

      # Frontend Deployment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Zip frontend artifact for deployment
        run: zip -r frontend.zip build/ package.json package-lock.json

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: frontend.zip

      - name: Download backend artifact for deployment
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact

      - name: Unzip backend artifact for deployment
        run: unzip -o backend.zip || true

      - name: Download frontend artifact for deployment
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact

      - name: Unzip frontend artifact for deployment
        run: unzip -o frontend.zip || true

      - name: 'Deploy Backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'textadventure'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_686FE9CADF644C2F8507F684BB702B59 }}
