name: Build and deploy React+Flask App to Azure Web App - textadventure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Navigate to frontend directory
        run: |
          cd frontend
          ls -la
          pwd  

      - name: Install frontend dependencies
        run: npm install ./frontend

      - name: Build frontend
        run: npm run build

      - name: Zip backend artifact for deployment
        run: zip -r backend.zip app.py __pycache__/*

      - name: Zip frontend artifact for deployment
        run: zip -r frontend.zip build/*

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend.zip

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: frontend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download backend artifact for deployment
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact

      - name: Download frontend artifact for deployment
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact

      - name: Unzip backend artifact for deployment
        run: unzip backend.zip

      - name: Unzip frontend artifact for deployment
        run: unzip frontend.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'textadventure'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_686FE9CADF644C2F8507F684BB702B59 }}
