name: Build and deploy React+Flask App to Azure Web App - textadventure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    trigger-subfolder-workflows:
        runs-on: ubuntu-latest
        steps:
        
        - name: Setup GitHub CLI
          uses: actions/checkout@v2
        - name: cd into frontend
          run: cd frontend
        - name: Run Frontend Workflow
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            gh workflow run .github/workflows/frontend-deploy.yml
            cd ..

        - name: cd into backend
          run: cd backend

        - name: Trigger Backend Workflow
          uses: actions/checkout@v2

        - name: Run Backend Workflow
          run: |
            cd backend
            gh workflow run backend-deploy.yml
            cd ..